# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fib_gen(max):
    x = 1
    y = 2
    yield x

    while y <= max:
        x, y = y, x + y
        yield x


for n in fib_gen(100):
    print(n)

result = sum(n for n in fib_gen(4000000) if n % 2 == 0)

print(f'The result is: {result}')
